#!/usr/bin/env python3
"""
Auto-generated tests for examples/example_basic_usage.py

This file was automatically generated by example_test_generator.py
from examples/example_basic_usage.py.
"""

import sys
import os
import tempfile
import shutil
import json

import importlib.util

# Load the example module
example_file_path = os.path.join(os.path.dirname(__file__), '../../examples/example_basic_usage.py')
spec = importlib.util.spec_from_file_location("example_module", example_file_path)
example_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(example_module)


class TestBasic_Usage:
    """Auto-generated tests for examples/example_basic_usage.py"""
    
    def setup_method(self):
        """Setup test environment"""
        self.test_dir = tempfile.mkdtemp(prefix="test_")
        self.original_cwd = os.getcwd()
        os.chdir(self.test_dir)
        
        # Create necessary directories based on example file structure
        self._setup_test_environment()
    
    def teardown_method(self):
        """Cleanup test environment"""
        os.chdir(self.original_cwd)
        shutil.rmtree(self.test_dir, ignore_errors=True)
    
    def _setup_test_environment(self):
        """Setup test environment - override in subclasses if needed"""
        # Create basic directory structure
        os.makedirs("examples", exist_ok=True)
        
        # Copy any existing config files from original examples directory
        original_examples = os.path.join(self.original_cwd, "examples")
        if os.path.exists(original_examples):
            for item in os.listdir(original_examples):
                src_path = os.path.join(original_examples, item)
                dst_path = os.path.join("examples", item)
                if os.path.isfile(src_path):
                    shutil.copy2(src_path, dst_path)
                elif os.path.isdir(src_path):
                    shutil.copytree(src_path, dst_path, dirs_exist_ok=True)

    def test_example_basic_test_generation(self):
        """Example of basic test generation functionality."""
        # Run the example function - if it raises an exception, the test will fail
        example_module.example_basic_test_generation()
        # If no exception is raised, the test passes
        assert True

    def test_example_cli_clean(self):
        """Example of using CLI to clean generated tests."""
        # Run the example function - if it raises an exception, the test will fail
        example_module.example_cli_clean()
        # If no exception is raised, the test passes
        assert True

    def test_example_cli_generate(self):
        """Example of using CLI to generate tests."""
        # Run the example function - if it raises an exception, the test will fail
        example_module.example_cli_generate()
        # If no exception is raised, the test passes
        assert True

    def test_example_cli_help(self):
        """Example of using CLI help functionality."""
        # Run the example function - if it raises an exception, the test will fail
        example_module.example_cli_help()
        # If no exception is raised, the test passes
        assert True

    def test_example_cli_regenerate(self):
        """Example of using CLI to regenerate tests."""
        # Run the example function - if it raises an exception, the test will fail
        example_module.example_cli_regenerate()
        # If no exception is raised, the test passes
        assert True

